name: Windows CI Demo

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a passing test
        run: python -c "assert 1+1==2; print('Test passed ✅')"
